[application]

# App (Project) Name
name = "homepage"

# Dioxus App Default Platform
# desktop, web
default_platform = "web"

# `build` & `serve` dist path
out_dir = "dist"

# resource (assets) file folder
asset_dir = "assets"

[web.app]

# HTML title tag content
title = "Harry Agustian"

[web.watcher]

# when watcher trigger, regenerate the `index.html`
reload_html = true

# which files or dirs will be watcher monitoring
watch_path = ["src", "assets"]

# include `assets` in web platform
[web.resource]

# CSS style file

style = [
  "/tailwind.css",
  "https://cdn.jsdelivr.net/npm/@dannymichel/proxima-nova@4.5.2/index.min.css",
]

# Javascript code file
script = [
  "https://cdn.jsdelivr.net/npm/tsparticles@1.43.1/tsparticles.min.js",
]

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
