on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: cargo test
    runs-on:
      labels: gha-runner-scale-set-homepage

    steps:
    - run: sudo apt update && sudo apt install -y curl build-essential pkg-config libssl-dev git
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - uses: taiki-e/install-action@cargo-llvm-cov
    - uses: taiki-e/install-action@nextest
    - run: cargo nextest run

  build:
    name: docker build and push
    needs: [test]
    runs-on:
      labels: gha-runner-scale-set-homepage

    steps:
      - uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.REGISTRY_DOMAIN }}/library/homepage
          tags: |
            type=sha
            type=ref,event=branch
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_DOMAIN }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
